2020-06-06 01:03:54,721 ERROR: Exception on /all_users [GET] [in c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\ajshe\microblog2\app\main\routes.py", line 39, in all_users
    profiles = User.query.all().paginate(page, current_app.config['POSTS_PER_PAGE'], False) #gets the postfrom users followed pages, .paginate is used to retrieve only the disired page of post results
AttributeError: 'list' object has no attribute 'paginate'
2020-06-06 01:04:36,036 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:04:37,365 ERROR: Exception on /all_users [GET] [in c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\ajshe\microblog2\app\main\routes.py", line 43, in all_users
    return render_template('all_users.html', title = _('All Users'), users=users, profiles=profiles, next_url=next_url, prev_url=prev_url)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ajshe\microblog2\app\templates\all_users.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ajshe\microblog2\app\templates\base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\ajshe\microblog2\app\templates\base.html", line 61, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\ajshe\microblog2\app\templates\all_users.html", line 8, in block "app_content"
    {% for user in profiles %}
TypeError: 'Pagination' object is not iterable
2020-06-06 01:08:17,719 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:08:18,782 ERROR: Exception on /all_users [GET] [in c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\ajshe\microblog2\app\main\routes.py", line 42, in all_users
    return render_template('all_users.html', title = _('All Users'), users=users, next_url=next_url, prev_url=prev_url)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ajshe\microblog2\app\templates\all_users.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ajshe\microblog2\app\templates\base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\ajshe\microblog2\app\templates\base.html", line 61, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\ajshe\microblog2\app\templates\all_users.html", line 8, in block "app_content"
    {% for user in users %}
TypeError: 'Pagination' object is not iterable
2020-06-06 01:08:52,538 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:09:43,821 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:10:18,170 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:10:59,700 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:11:38,953 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:12:01,043 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:13:42,674 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:14:44,705 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:18:47,669 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:19:01,205 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:20:24,162 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:21:06,015 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:21:53,853 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:22:10,624 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:28:36,426 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:29:15,073 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:29:48,181 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:30:15,332 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-06 01:30:28,046 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
